### ISSUE TITLE
Sobre el proyecto/Gacetilla de prensa/proyecto UVdesk y web de DATA

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DondeReciclo-3#25]
From Plantilla--NombreDeProyecto-Version-backSiAplica created by [danielcarranza](https://github.com/danielcarranza): datauy/Plantilla--NombreDeProyecto-Version-backSiAplica#25  

Usar plantilla: https://docs.google.com/document/d/1l_g7VObON7gYuq7SzGTSXa_VvWxu1VRw3EMDvDLBPwQ/edit#heading=h.imzjv2bfebss

**Nombre del proyecto**
- [ ] Descripción breve en base a metadescripción (#10) y usando palabras clave definidas (#4)

**Sobre el proyecto**
- [ ] Qué problema queremos solucionar
- [ ] Cómo la herramienta lo hace

**Enlaces de interés**
- [ ] Web del proyecto
- [ ] Descarga apps
- [ ] Ayuda del proyecto

**Contactos**
- [ ] Correos sobre el proyecto
- [ ] Formularios

**Materiales para difusión (#24)**
- [ ] Palabras clave
- [ ] Publicaciones para lanzamiento en base a metadescripción (#10) y usando palabras clave definidas (#4)
- [ ] Enlaces a todos los materiales gráficos Kit de Prensa
- [ ] Enlaces a todos los materiales gráficos RRSS
- [ ] Enlace artículo de lanzamiento del blog (#27)

**Quiénes somos**
- [ ] Información de data y aliados del pie de página (#3)

**Antecedentes**
- [ ] Origen

**Datos y Servicios Abiertos**
- [ ] Datos abiertos que usa la aplicación
- [ ] Servicios abiertos que usa la aplicación
- [ ] Otros datos

**Software Libre**
- [ ] Disponible
- [ ] Licencia
- [ ] Botones GitHub

**Términos y condiciones**
- [ ] Texto estándar TyC
- [ ] Texto estándar Procesamiento de datos
- [ ] Contenido bajo licencia CC-BY 4.0
- [ ] Texto estándar lenguaje inclusivo

**Papers, casos de estudio y otros materiales**
- [ ] Enlaces

**Reconocimientos**
- [ ] Enlaces

**Cómo se financia**
- [ ] Explicación

**Fotos**
- [ ] Enlace a colección en Flickr

**Notas de prensa**
- [ ] Carga filtrada por tag de Pocket

**Comment by danielcarranza** [comment]
Kamino cloned this issue to [datauy/UruguayLeaks](https://github.com/datauy/UruguayLeaks/issues/11)
