### ISSUE TITLE
Materiales para posteos en RRSS

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DondeReciclo-3#36]
From Plantilla--NombreDeProyecto-Version-backSiAplica created by [danielcarranza](https://github.com/danielcarranza): datauy/Plantilla--NombreDeProyecto-Version-backSiAplica#26  

Usar plantilla gráfica: https://drive.google.com/open?id=1FMd516v5CyM6cCW4CFw6IxhtSjWdabW0

- [ ] Tres imágenes difrentes (#24)
- [ ] Posteos para lanzamiento en base a metadescripción (#10) y usando palabras clave definidas (#4)
- [ ] Enlazar al sitio
- [ ] Etiquetar a aliados
- [ ] Publicar artículo de lanzamiento del blog (#27)

**Comment by danielcarranza** [comment]
Kamino cloned this issue to [datauy/UruguayLeaks](https://github.com/datauy/UruguayLeaks/issues/21)
